language: python
python:
    - 3.6
install:
    - pip3 install -r requirements.txt
script:
    # - cd wk9/airline3
    # - python3 manage.py test
    - cd project01
    - python3 test_app.py
branches:
  only:
  - master
  - /.*/
