language: python
python:
    - 3.6
install:
    - pip3 install -r requirements.txt
before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
script:
    - cd wk9/airline3
    - python3 manage.py test
    # - cd project01
    # - python3 test_app.py
branches:
  only:
  - master
  # - /.*/
